language: minimal
dist: xenial

script:
- docker build -t $DOCKER_USERNAME/slackbot:1.3 .

after_success:
- if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin;
    docker push $DOCKER_USERNAME/slackbot:1.3;
  fi

notifications:
  slack:
    secure: "C02hkGLNg5eUhX1iEFp0wHutDCiXqA3xApY2kXS3vQnXxLEYXJ+ArMYUtGVRJywKiff0NhdOxog34O0r+c7HBHH8R/S/Xv8yLpiAELF4vWt0ko1LoDzFe93wY0zhzBHRK4hR7WQ8HKflQbh829lhWX7UjEgujY9uLEIqiAlJoNSebmEV0kcW014416ZtyGOgQViDekgsRB+hXlzIs1oYPS8CH8FvkFDYFyy8utYhp7n35BkUhA35Zp0v3NNyHjDH1o7VUqzkGp8IzprBK4Z8cEsdIM5xZQ4XcPVlU/Y5DdMY34R4f8YPVDWa99t6NDh0bkfjMhOuqJ3ZfBaDtDx4/YNJUJMitYKagzkt8biD57sjwZKNvQ31d6UNNOVkFjXgmtTe1GbGhKNgZiOKfBgSam6aE6K+pXTnDF8g6Xur41jOsXPrpO0Q+xBU8cMBk+cEhYx114V1QCMU5wf/Wm7YhrJh/FYp+/6TLUFxKylAOOl9eRyaDbN1YBne4fcC+692d0UekR16yqbwY9WGgqSoOak/w/dDaDh0HclrIxmM4pSBpfKj4uhfSgO+jdIJDGK82CqX9S1JO9C4yU638aRSwXaYyEoNebd6u9f7MF4ruBnrSZrvphLxBnVyKNZ8Cp7vyIA8V505Qa6+07eIIl8ipvOPXzlbN1u4ADY9gR0ywQY="
