dist: xenial

script:
  - docker build -t $DOCKER_USERNAME/slackbot:1.1 .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/slackbot:1.1
