apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: slackbot
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io